import {useEffect, useState} from 'react';
import {Alert, Button, Card, Col, Empty, Input, InputNumber, Popconfirm, Row, Skeleton, Space, Tag, Typography} from 'antd';
import {DeleteOutlined, PlusOutlined} from '@ant-design/icons';
import {get} from '../api/http';
import {multiblockDesignListSchema, type MultiblockDesign} from '../types/api';
import {IsoPreview} from '../features/multiblocks/IsoPreview';
import {demoMultiblocks} from '../mocks/devData';
import '../features/layout/master-detail-layout.css';
import '../styles-multiblock.css';
import {MasterDetailLayout} from '../features/layout/MasterDetailLayout';

type DataSource = 'server' | 'demo';
type GridPoint = {x: number; z: number};

function parseStructure(value: string): Record<string, unknown> {
  try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {layers: []}; } catch { return {layers: []}; }
}

function GridEditor({structureJson, setStructureJson, sizeX, sizeY, sizeZ, setMessage, setError}: {structureJson: string; setStructureJson: (value: string) => void; sizeX: number; sizeY: number; sizeZ: number; setMessage: (value: string) => void; setError: (value: string) => void}) {
  const [layerIndex, setLayerIndex] = useState(0); const [selected, setSelected] = useState<GridPoint | null>(null); const [dragSource, setDragSource] = useState<GridPoint | null>(null); const [cellValue, setCellValue] = useState('air'); const [brushValue, setBrushValue] = useState('air');
  const readLayers = () => {try {const parsed = JSON.parse(structureJson) as {layers?: unknown[][][]}; return Array.isArray(parsed.layers) ? parsed.layers : [];} catch {return [];}};
  const readCell = (point: GridPoint) => {const layer = readLayers()[layerIndex]; const row = Array.isArray(layer?.[point.z]) ? layer[point.z] : []; return String(row?.[point.x] ?? 'air');};
  const selectCell = (point: GridPoint) => {setSelected(point); setCellValue(readCell(point));};
  const writeGrid = (mutate: (layers: unknown[][][]) => void) => {try {const parsed = JSON.parse(structureJson) as {layers?: unknown[][][]}; const layers = Array.isArray(parsed.layers) ? parsed.layers : []; mutate(layers); parsed.layers = layers; setStructureJson(JSON.stringify(parsed, null, 2)); return true;} catch {setError('请先修正结构 JSON，才能修改网格'); return false;}};
  const writeCell = () => {if (!selected) return; if (writeGrid(layers => {const layer = Array.isArray(layers[layerIndex]) ? layers[layerIndex] : []; const row = Array.isArray(layer[selected.z]) ? layer[selected.z] : []; while (row.length <= selected.x) row.push('air'); row[selected.x] = cellValue.trim() || 'air'; layer[selected.z] = row; layers[layerIndex] = layer;})) setMessage(`已修改第 ${layerIndex} 层 (${selected.x}, ${selected.z})，保存后生效`);};
  const moveCell = (target: GridPoint) => {if (!dragSource || (dragSource.x === target.x && dragSource.z === target.z)) return; if (writeGrid(layers => {const layer = Array.isArray(layers[layerIndex]) ? layers[layerIndex] : []; const sourceRow = Array.isArray(layer[dragSource.z]) ? layer[dragSource.z] : []; const targetRow = Array.isArray(layer[target.z]) ? layer[target.z] : []; const sourceValue = sourceRow[dragSource.x] ?? 'air'; const targetValue = targetRow[target.x] ?? 'air'; while (sourceRow.length <= dragSource.x) sourceRow.push('air'); while (targetRow.length <= target.x) targetRow.push('air'); sourceRow[dragSource.x] = targetValue; targetRow[target.x] = sourceValue; layer[dragSource.z] = sourceRow; layer[target.z] = targetRow; layers[layerIndex] = layer;})) setMessage(`已交换第 ${layerIndex} 层 (${dragSource.x}, ${dragSource.z}) 与 (${target.x}, ${target.z})，保存后生效`); setDragSource(null);};
  const fillLayer = () => {if (writeGrid(layers => {const layer = Array.from({length: sizeZ}, () => Array.from({length: sizeX}, () => brushValue.trim() || 'air')); layers[layerIndex] = layer;})) setMessage(`已将第 ${layerIndex} 层全部刷为 ${brushValue.trim() || 'air'}，保存后生效`);};
  const cells = Array.from({length: Math.max(1, sizeX * sizeZ)}, (_, index) => {const x = index % Math.max(1, sizeX); const z = Math.floor(index / Math.max(1, sizeX)); return {x, z, value: readCell({x, z})};});
  return <Card size="small" title="结构网格（可点击或拖拽）"><Space style={{display: 'flex', marginBottom: 8}} wrap><Typography.Text type="secondary">层 Y</Typography.Text><InputNumber min={0} max={Math.max(0, sizeY - 1)} value={layerIndex} onChange={value => setLayerIndex(value ?? 0)}/>{selected && <><Typography.Text type="secondary">格子 ({selected.x}, {selected.z})</Typography.Text><Input value={cellValue} onChange={event => setCellValue(event.target.value)} style={{width: 180}}/><Button onClick={writeCell}>写入格子</Button></>}<Typography.Text type="secondary">整层刷块</Typography.Text><Input value={brushValue} onChange={event => setBrushValue(event.target.value)} style={{width: 150}}/><Button onClick={fillLayer}>填充当前层</Button></Space><div style={{display: 'grid', gridTemplateColumns: `repeat(${Math.max(1, sizeX)}, minmax(70px, 1fr))`, gap: 4, padding: 8, border: '1px solid #e5e7eb', borderRadius: 8}}>{cells.map(cell => <Button key={`${cell.x}-${cell.z}`} size="small" draggable onDragStart={() => setDragSource({x: cell.x, z: cell.z})} onDragOver={event => event.preventDefault()} onDrop={() => moveCell({x: cell.x, z: cell.z})} type={selected?.x === cell.x && selected.z === cell.z ? 'primary' : 'default'} onClick={() => selectCell({x: cell.x, z: cell.z})}>{cell.value}</Button>)}</div><Typography.Text type="secondary">拖拽一个格子到另一个格子可交换方块内容；填充操作保存后才会写入服务器。</Typography.Text></Card>;
}

export function MultiblocksPage() {
  const [items, setItems] = useState<MultiblockDesign[]>([]); const [source, setSource] = useState<DataSource>('server'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [designId, setDesignId] = useState(''); const [editingId, setEditingId] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState(''); const [designName, setDesignName] = useState(''); const [sizeX, setSizeX] = useState(3); const [sizeY, setSizeY] = useState(3); const [sizeZ, setSizeZ] = useState(3); const [structure, setStructure] = useState<Record<string, unknown> | null>(null); const [controller, setController] = useState<Record<string, unknown> | null>(null); const [controllerPoint, setControllerPoint] = useState({x: 0, y: 0, z: 0}); const [structureJson, setStructureJson] = useState(''); const [controllerJson, setControllerJson] = useState(''); const [creating, setCreating] = useState(false); const [message, setMessage] = useState(''); const [formError, setFormError] = useState('');
  const load = () => get('/api/multiblocks', multiblockDesignListSchema).then(rows => {setItems(rows); setSource('server'); setError('');}).catch((reason: unknown) => {setError(reason instanceof Error ? reason.message : '加载多方块设计失败'); setItems(demoMultiblocks); setSource('demo');}).finally(() => setLoading(false));
  useEffect(() => {let active = true; get('/api/multiblocks', multiblockDesignListSchema).then(rows => {if (active) {setItems(rows); setSource('server'); setError('');}}).catch((reason: unknown) => {if (active) {setError(reason instanceof Error ? reason.message : '加载多方块设计失败'); setItems(demoMultiblocks); setSource('demo');}}).finally(() => active && setLoading(false)); return () => {active = false;};}, []);
  const create = async () => {if (!designId.trim() || !designName.trim()) {setFormError('请填写设计 ID 和名称'); return;} setCreating(true); setFormError(''); setMessage(''); const layers = Array.from({length: sizeY}, () => Array.from({length: sizeZ}, () => Array.from({length: sizeX}, () => 'air'))); let nextStructure: Record<string, unknown> = editingId && structure ? structure : {layers}; let nextController: Record<string, unknown> = editingId && controller ? controller : {x: 0, y: 0, z: 0}; if (editingId) {try {const parsedStructure = JSON.parse(structureJson); const parsedController = JSON.parse(controllerJson); if (!parsedStructure || Array.isArray(parsedStructure) || typeof parsedStructure !== 'object') throw new Error('结构必须是 JSON 对象'); if (!parsedController || Array.isArray(parsedController) || typeof parsedController !== 'object') throw new Error('控制器必须是 JSON 对象'); nextStructure = parsedStructure as Record<string, unknown>; nextController = parsedController as Record<string, unknown>;} catch (reason) {setFormError(reason instanceof Error ? `JSON 格式错误：${reason.message}` : 'JSON 格式错误'); setCreating(false); return;}} try {const payload = {designId: designId.trim(), name: designName.trim(), sizeX, sizeY, sizeZ, structure: nextStructure, controller: nextController}; const response = await fetch(editingId ? `/api/multiblocks/${encodeURIComponent(editingId)}` : '/api/multiblocks', {method: editingId ? 'PUT' : 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify(payload)}); if (!response.ok) throw new Error(`HTTP ${response.status}`); setMessage(editingId ? '已保存修改，结构和控制器已更新' : '已创建，正在刷新列表'); setDesignId(''); setDesignName(''); setEditingId(null); setStructure(null); setController(null); setStructureJson(''); setControllerJson(''); await load();} catch (reason) {setFormError(reason instanceof Error ? reason.message : '保存失败');} finally {setCreating(false);}};
  const remove = async (id: string) => {setFormError(''); try {const response = await fetch(`/api/multiblocks/${encodeURIComponent(id)}`, {method: 'DELETE'}); if (!response.ok) throw new Error(`HTTP ${response.status}`); setMessage('设计已删除'); await load();} catch (reason) {setFormError(reason instanceof Error ? reason.message : '删除失败');}};
  const writeControllerPoint = () => {const next = {...(controller || {}), ...controllerPoint}; setController(next); setControllerJson(JSON.stringify(next, null, 2)); setMessage(`已写入控制器坐标 (${controllerPoint.x}, ${controllerPoint.y}, ${controllerPoint.z})，点击保存修改后生效`);};
  const edit = (design: MultiblockDesign) => {setEditingId(design.designId); setSelectedId(design.designId); setDesignId(design.designId); setDesignName(design.name); setSizeX(design.sizeX); setSizeY(design.sizeY); setSizeZ(design.sizeZ); setStructure(design.structure); setController(design.controller); setControllerPoint({x: Number(design.controller.x) || 0, y: Number(design.controller.y) || 0, z: Number(design.controller.z) || 0}); setStructureJson(JSON.stringify(design.structure, null, 2)); setControllerJson(JSON.stringify(design.controller, null, 2)); setMessage('已载入设计，可点击网格或拖拽交换方块');};
  const startNew = () => {setEditingId(null); setSelectedId(''); setDesignId(''); setDesignName(''); setStructure(null); setController(null); setControllerPoint({x: 0, y: 0, z: 0}); setStructureJson(''); setControllerJson(''); setMessage('');};
return <main className="mods-multiblock">
  <MasterDetailLayout
    list={<>
      <div className="page-heading"><div><Typography.Title level={2}>多方块设计</Typography.Title><Typography.Paragraph type="secondary">创建、编辑、删除结构草稿，预览控制器位置和版本。</Typography.Paragraph></div></div>
      {error && <Alert type="warning" showIcon title="接口加载失败，已切到演示模板" description={error}/>}
      <Space className="mb-list-actions"><Button type="primary" icon={<PlusOutlined/>} onClick={startNew}>新建</Button>{!loading && <Typography.Text type="secondary">{items.length} 个设计</Typography.Text>}</Space>
      {loading ? <Card variant="borderless"><Skeleton active paragraph={{rows: 5}}/></Card> : !items.length ? <Empty description="暂无多方块设计记录"/> : <div className="mb-design-list">{items.map(d => <Card key={d.designId} variant="borderless" className={selectedId === d.designId ? 'mb-design-card mb-design-selected' : 'mb-design-card'} onClick={() => edit(d)} role="button" tabIndex={0} onKeyDown={event => event.key === 'Enter' && edit(d)}><div className="mb-design-title"><Typography.Text strong>{d.name}</Typography.Text><div className="muted">{d.designId}</div></div><div className="multiblock-meta"><span>{d.sizeX} × {d.sizeY} × {d.sizeZ}</span><Tag color="blue">v{d.version}</Tag><span>revision {d.revision}</span></div><IsoPreview sizeX={d.sizeX} sizeY={d.sizeY} sizeZ={d.sizeZ} structure={d.structure} controller={d.controller}/><div className="mb-card-actions"><Popconfirm title="删除这个结构设计？" description="删除后不可恢复。" onConfirm={() => remove(d.designId)} okText="删除" cancelText="取消"><Button size="small" danger type="text" icon={<DeleteOutlined/>} aria-label={"删除 " + d.name} onClick={event => event.stopPropagation()}/></Popconfirm></div></Card>)}</div>}
    </>}
    detail={<div className="mb-detail-editor">
      <div className="page-heading"><div><Typography.Title level={3}>{editingId ? '编辑设计：' + editingId : '新建设计'}</Typography.Title><Typography.Paragraph type="secondary">{editingId ? '修改结构与控制器并保存' : '填写信息并创建结构草稿'}</Typography.Paragraph></div></div>
      <Space wrap><Input placeholder="设计 ID" value={designId} disabled={Boolean(editingId)} onChange={event => setDesignId(event.target.value)}/><Input placeholder="名称" value={designName} onChange={event => setDesignName(event.target.value)}/><InputNumber min={1} max={32} value={sizeX} onChange={value => setSizeX(value ?? 1)} addonBefore="X"/><InputNumber min={1} max={32} value={sizeY} onChange={value => setSizeY(value ?? 1)} addonBefore="Y"/><InputNumber min={1} max={32} value={sizeZ} onChange={value => setSizeZ(value ?? 1)} addonBefore="Z"/><Button type="primary" loading={creating} onClick={create}>{editingId ? '保存修改' : '创建结构草稿'}</Button>{editingId && <Button onClick={startNew}>取消编辑</Button>}</Space>
      {editingId && <Row gutter={[16,16]} style={{marginTop: 16}}><Col xs={24} lg={16}><GridEditor structureJson={structureJson} setStructureJson={setStructureJson} sizeX={sizeX} sizeY={sizeY} sizeZ={sizeZ} setMessage={setMessage} setError={setFormError}/><Typography.Text strong style={{display: 'block', marginTop: 12}}>3D 结构编辑</Typography.Text><IsoPreview sizeX={sizeX} sizeY={sizeY} sizeZ={sizeZ} structure={parseStructure(structureJson)} controller={controller || undefined} onChangeStructure={next => {setStructureJson(JSON.stringify(next, null, 2)); setMessage('已从 3D 视图写入当前草稿，点击保存修改后生效');}} onChangeController={next => {setController(next); setControllerPoint({x: Number(next.x) || 0, y: Number(next.y) || 0, z: Number(next.z) || 0}); setControllerJson(JSON.stringify(next, null, 2)); setMessage('已从 3D 视图移动控制器到 (' + next.x + ', ' + next.y + ', ' + next.z + ')，点击保存修改后生效');}}/><Typography.Text strong style={{display: 'block', marginTop: 12}}>结构 JSON</Typography.Text><Input.TextArea rows={8} value={structureJson} onChange={event => setStructureJson(event.target.value)} spellCheck={false}/></Col><Col xs={24} lg={8}><Typography.Text strong>控制器坐标</Typography.Text><Space wrap style={{display: 'flex', margin: '8px 0 12px'}}><InputNumber min={0} max={Math.max(0, sizeX - 1)} value={controllerPoint.x} onChange={value => setControllerPoint(point => ({...point, x: value ?? 0}))} addonBefore="X"/><InputNumber min={0} max={Math.max(0, sizeY - 1)} value={controllerPoint.y} onChange={value => setControllerPoint(point => ({...point, y: value ?? 0}))} addonBefore="Y"/><InputNumber min={0} max={Math.max(0, sizeZ - 1)} value={controllerPoint.z} onChange={value => setControllerPoint(point => ({...point, z: value ?? 0}))} addonBefore="Z"/><Button onClick={writeControllerPoint}>写入坐标</Button></Space><Typography.Text strong>控制器 JSON</Typography.Text><Input.TextArea rows={10} value={controllerJson} onChange={event => setControllerJson(event.target.value)} spellCheck={false}/></Col></Row>}
      {editingId && <Typography.Text type="secondary" style={{display: 'block', marginTop: 12}}>保存前会校验两个 JSON 必须是对象；保存后版本和 revision 会递增。</Typography.Text>}
      {formError && <Alert style={{marginTop: 12}} type="error" showIcon title="操作失败" description={formError}/>}
      {message && <Alert style={{marginTop: 12}} type="success" showIcon title={message}/>}
    </div>}
  />
</main>;
}