import {useEffect, useState} from 'react';
import {App, Button, Divider, Form, Input, InputNumber, Progress, Select, Space, Steps, Switch, Tag} from 'antd';
import {
  ApartmentOutlined, ArrowRightOutlined, CheckCircleFilled, CheckOutlined, CloudDownloadOutlined,
  CodeOutlined, CompassOutlined, DeleteOutlined, ExportOutlined, FileZipOutlined,
  FolderOpenOutlined, InfoCircleOutlined, LinkOutlined, MoreOutlined, PlusOutlined,
  ReloadOutlined, SearchOutlined, SettingOutlined, ToolOutlined, UploadOutlined, WarningFilled,
} from '@ant-design/icons';
import {useNavigate, useParams} from 'react-router-dom';
import {WorkbenchButton, WorkbenchCard, WorkbenchSectionHeader} from '../ui/workbench/Workbench';
import './pack-pages.css';
import {addMod, getPack, listMods, listPacks, removeMod, searchMods, updateMod} from '../features/pack/api';
import type {Pack, Mod} from '../features/pack/api';

const packName = (id?: string) => id === 'demo' ? '星港远征' : '科技魔法';

function PackContext({active = '概览', action}: {active?: string; action?: React.ReactNode}) {
  const {id} = useParams();
  const navigate = useNavigate();
  const name = packName(id);
  return <header className="pack-context">
    <button className="pack-context-back" onClick={() => navigate('/packs')} aria-label="返回整合包列表">整合包</button>
    <span className="pack-context-sep">/</span>
    <div className="pack-context-cover">{name.slice(0, 1)}</div>
    <div className="pack-context-title"><strong>{name}</strong><span>MC 1.20.1 · NeoForge · v1.2.0</span></div>
    <Tag color="green">已保存</Tag>
    <div className="pack-context-tabs">{active}</div>
    <div className="pack-context-action">{action}</div>
  </header>;
}

const mods = [
  {name: 'Create', author: 'simibubi', version: '0.5.1-f', downloads: '18.4M', status: '已安装', color: 'orange', desc: '让机械动力与自动化成为整合包的核心。'},
  {name: 'JEI', author: 'mezz', version: '15.3.0.4', downloads: '52.1M', status: '已安装', color: 'green', desc: '在游戏内查看配方、用途与合成路径。'},
  {name: 'Sophisticated Backpacks', author: 'P3pp3rF1y', version: '3.20.5.1', downloads: '9.2M', status: '待确认', color: 'gold', desc: '可升级的背包与仓储，适合长线探索。'},
  {name: 'Applied Energistics 2', author: 'unpredictable', version: '15.2.14', downloads: '23.6M', status: '可添加', color: 'blue', desc: '构建网络化存储与自动化生产线。'},
];

export function PacksPage() {
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const [packs, setPacks] = useState<Pack[]>([]); const [error, setError] = useState('');
  useEffect(() => { void listPacks().then(setPacks).catch(e => setError(e instanceof Error ? e.message : String(e))); }, []);
  const visible = packs.filter(p => p.name.includes(query));
  return <div className="workspace-page">
    <div className="page-heading"><div><span className="eyebrow">WORKSPACE / PACKS</span><h1>整合包</h1><p>每个包都是一条独立的设计路径，从选模组一直走到交付。</p></div><Space><Button icon={<UploadOutlined/>}>导入整合包</Button><WorkbenchButton tone="primary" icon={<PlusOutlined/>}>新建整合包</WorkbenchButton></Space></div>
    <WorkbenchCard className="pack-overview-strip"><div><span className="strip-label">当前工作集</span><strong>3 个整合包</strong></div><div><span className="strip-label">最近解决</span><strong className="text-success">12 个问题</strong></div><div><span className="strip-label">需要处理</span><strong className="text-warning">4 个冲突</strong></div><Input prefix={<SearchOutlined/>} placeholder="筛选整合包" value={query} onChange={e => setQuery(e.target.value)} allowClear /></WorkbenchCard>
    <WorkbenchCard className="pack-table-card"><WorkbenchSectionHeader title="全部整合包" action={<span className="db-muted">按最后编辑排序</span>}/>{error && <div className="empty-inline">加载失败：{error}</div>}<div className="pack-table pack-table-head"><span>包名称</span><span>环境</span><span>模组</span><span>状态</span><span>最后编辑</span><span /></div>{visible.map(p => <button className="pack-table pack-table-row" key={p.id} onClick={() => navigate(`/packs/${p.id}`)}><span className="pack-table-name"><span className={`pack-mini-cover pack-mini-${p.id}`}>{p.name.slice(0, 1)}</span><strong>{p.name}</strong><Tag>{p.packVersion}</Tag></span><span><Tag>MC {p.mcVersion}</Tag><Tag>{p.loader}</Tag></span><span className="tabular">—</span><span className="text-success tabular">{p.status}</span><span className="db-muted">{p.updatedAt ?? p.createdAt ?? '—'}</span><span><MoreOutlined /></span></button>)}{!error && visible.length === 0 && <div className="empty-inline">没有匹配的整合包。试试其他名称。</div>}</WorkbenchCard>
  </div>;
}

export function PackWorkbenchPage() {
  const {id} = useParams(); const navigate = useNavigate(); const {message} = App.useApp(); const [pack,setPack]=useState<Pack|null>(null); const [items,setItems]=useState<Mod[]>([]); const [error,setError]=useState('');
  useEffect(()=>{ if (!id) return; void Promise.all([getPack(id),listMods(id)]).then(([p,m])=>{setPack(p);setItems(m)}).catch(e=>setError(e instanceof Error?e.message:String(e))); },[id]);
  const rows = items.slice(0,3).map(m=>({name:m.displayName,author:m.source,version:m.versionId||'—',downloads:'',status:m.status,color:'blue',desc:m.fileName}));
  return <div className="workspace-page"><PackContext action={<WorkbenchButton tone="primary" onClick={() => navigate(`/packs/${id}/publish`)} icon={<FileZipOutlined/>}>开始打包</WorkbenchButton>}/><div className="page-heading compact"><div><span className="eyebrow">PACK WORKBENCH</span><h1>{pack?.name ?? '加载中…'}</h1><p>选择模组、锁定依赖，处理会阻塞交付的冲突。</p></div><Button icon={<SettingOutlined/>} onClick={() => message.info('包设置将在此处打开')}>包设置</Button></div>{error&&<div className="empty-inline">加载失败：{error}</div>}<div className="workbench-grid"><main className="workbench-main"><WorkbenchCard className="mod-search-card"><div className="result-note"><span><strong>{items.length}</strong> 个已选择模组</span><Button type="link" onClick={() => navigate(`/packs/${id}/mods`)}>查看完整搜索 <ArrowRightOutlined/></Button></div>{rows.map(m=><ModRow key={m.name} mod={m} onAction={()=>message.success(`${m.name} 已加入整合包`)}/>)}{!error&&items.length===0&&<div className="empty-inline">当前还没有模组。</div>}<Button block type="dashed" className="list-more" onClick={()=>navigate(`/packs/${id}/mods`)}>搜索并添加更多模组</Button></WorkbenchCard></main><PackHealthRail id={id}/></div></div>;
}

function ModRow({mod, onAction}: {mod: typeof mods[number]; onAction: () => void}) { return <div className="mod-row"><span className="mod-symbol"><CodeOutlined/></span><div className="mod-row-main"><strong>{mod.name}</strong><span>{mod.author} · {mod.version} · {mod.downloads} 下载</span><small>{mod.desc}</small></div><Tag color={mod.color}>{mod.status}</Tag><Button size="small" onClick={onAction}>{mod.status === '已安装' ? '查看' : '添加'}</Button></div>; }

function PackHealthRail({id}: {id?: string}) { const navigate = useNavigate(); return <aside className="pack-health-rail"><div className="health-kicker">PACK HEALTH</div><h2>包健康</h2><div className="health-score"><strong>86</strong><span>/ 100</span><Tag color="gold">需要关注</Tag></div><div className="health-list"><div><CheckCircleFilled className="text-success"/><span>依赖已锁定</span><b>142</b></div><div><WarningFilled className="text-danger"/><span>待解决冲突</span><b className="text-danger">3</b></div><div><InfoCircleOutlined className="text-info"/><span>可更新模组</span><b>5</b></div><div><CheckOutlined className="text-success"/><span>内容编辑</span><b>26</b></div></div><Divider/><Button block onClick={() => navigate(`/packs/${id}/dependencies`)}>处理冲突 <ArrowRightOutlined/></Button></aside>; }

export function PackModsPage() { const {id} = useParams(); const {message} = App.useApp(); const [query, setQuery] = useState(''); const [items,setItems]=useState<Mod[]>([]); const [error,setError]=useState(''); const refresh=()=>id&&listMods(id).then(setItems).catch(e=>setError(e instanceof Error?e.message:String(e))); useEffect(()=>{void refresh();},[id]); const runSearch=()=>{if(!id)return; void searchMods(id,{provider:'curseforge',query,limit:20}).then(v=>setItems(v.items.map(p=>({id:p.id,packId:id,source:'curseforge',projectId:p.id,displayName:p.name,fileName:'',status:'available',required:true,addedAt:'',updatedAt:''})))).catch(e=>setError(e instanceof Error?e.message:String(e)));}; const filtered = items.filter(m => `${m.displayName}${m.source}`.toLowerCase().includes(query.toLowerCase())); const mutate=async(fn:()=>Promise<unknown>,ok:string)=>{try{await fn();message.success(ok);void refresh();}catch(e){message.error(e instanceof Error?e.message:String(e));}}; return <div className="workspace-page"><PackContext active="模组"/><div className="page-heading compact"><div><span className="eyebrow">MOD CATALOG / {packName(id).toUpperCase()}</span><h1>模组</h1><p>搜索结果会自动按当前包的 MC 版本与加载器筛选。</p></div></div><WorkbenchCard className="catalog-card"><div className="catalog-toolbar"><Input size="large" allowClear autoFocus prefix={<SearchOutlined/>} placeholder="搜索模组名、作者或 Mod ID" value={query} onChange={e => setQuery(e.target.value)} onPressEnter={runSearch}/><Button icon={<ReloadOutlined/>} onClick={runSearch}>重新检索</Button></div>{error&&<div className="empty-inline">加载失败：{error}</div>}<div className="catalog-tabs"><button className="active">模组 <span>{filtered.length}</span></button></div>{filtered.map(m => <ModRow key={m.id} mod={{name:m.displayName,author:m.source,version:m.versionId||'—',downloads:'',status:m.status,color:'blue',desc:m.fileName}} onAction={()=>m.projectId&&id?void mutate(()=>m.status==='disabled'?updateMod(id,m.id,{status:'enabled'}):removeMod(id,m.id),m.status==='disabled'?'已启用':'已移除'):void mutate(()=>addMod(id!,{provider:m.source,projectId:m.projectId,versionId:m.versionId||'',required:true}),'已提交添加')}/>)}{!error&&!filtered.length&&<div className="empty-inline">没有找到匹配结果。</div>}</WorkbenchCard></div>; }

const conflicts = [{name: 'Create 与 Flywheel', type: '版本冲突', detail: 'Create 需要 Flywheel 0.6.10，当前锁定为 0.6.9。', severity: 'high'}, {name: 'JEI 与 Farmer’s Delight', type: '兼容提示', detail: '建议升级 JEI 至 15.3.0.5 以修复配方预览问题。', severity: 'medium'}, {name: '结构生成规则', type: '内容冲突', detail: '两个内容编辑同时修改了地下矿脉的权重。', severity: 'high'}];
export function DependenciesPage() { const {id} = useParams(); const {message} = App.useApp(); const [resolved, setResolved] = useState<string[]>([]); const remaining = conflicts.filter(c => !resolved.includes(c.name)); return <div className="workspace-page"><PackContext active="依赖与冲突"/><div className="page-heading compact"><div><span className="eyebrow">DEPENDENCIES / RESOLUTION</span><h1>依赖与冲突</h1><p>把版本问题变成明确的选择，解决后再进入发布检查。</p></div><WorkbenchButton tone="primary" icon={<CheckOutlined/>} onClick={() => {setResolved(conflicts.map(c => c.name)); message.success('冲突检查已完成');}}>全部尝试解决</WorkbenchButton></div><div className="dependency-grid"><main><div className="resolution-summary"><div><span>已解决</span><strong className="text-success">{resolved.length + 12}</strong></div><div><span>待处理</span><strong className="text-danger">{remaining.length}</strong></div><div><span>自动建议</span><strong>2</strong></div></div><WorkbenchCard className="conflict-card"><WorkbenchSectionHeader title="待处理项" action={<Button type="text" icon={<ReloadOutlined/>}>重新检查</Button>}/>{remaining.map(c => <div className="conflict-row" key={c.name}><span className={`conflict-mark ${c.severity}`}><WarningFilled/></span><div><strong>{c.name}</strong><Tag color={c.severity === 'high' ? 'red' : 'gold'}>{c.type}</Tag><p>{c.detail}</p></div><Button onClick={() => {setResolved(v => [...v, c.name]); message.success(`${c.name} 已解决`);}}>查看建议</Button></div>)}{!remaining.length && <div className="resolved-state"><CheckCircleFilled/><strong>所有冲突已解决</strong><span>可以继续进行发布检查。</span></div>}</WorkbenchCard></main><aside className="dependency-rail"><h2>解决策略</h2><p>优先使用锁定文件中的兼容版本。手动覆盖前，会保留一条可撤销记录。</p><Divider/><label>策略</label><Select defaultValue="兼容性优先" options={['兼容性优先', '最新版本优先', '手动选择'].map(v => ({label: v, value: v}))}/><div className="rail-note"><ToolOutlined/> 依赖锁定范围：{packName(id)} / NeoForge 1.20.1</div></aside></div></div>; }

export function ContentEditorPage() { const [type, setType] = useState('配方'); const [saved, setSaved] = useState(true); const {message} = App.useApp(); return <div className="workspace-page editor-page"><PackContext active="内容编辑" action={<Space><Tag color={saved ? 'green' : 'gold'}>{saved ? '已保存' : '有未保存修改'}</Tag><WorkbenchButton tone="primary" onClick={() => {setSaved(true); message.success('草稿已保存');}}>保存草稿</WorkbenchButton></Space>}/><div className="page-heading compact"><div><span className="eyebrow">CONTENT STUDIO</span><h1>内容编辑</h1><p>在包内配置配方、结构生成和矿脉规则，不离开工作台。</p></div></div><div className="editor-layout"><aside className="editor-rail"><div className="rail-label">内容类型</div>{['配方', '结构', '矿脉'].map((v, i) => <button key={v} className={type === v ? 'selected' : ''} onClick={() => {setType(v); setSaved(false);}}><span className="rail-icon">{i === 0 ? <ToolOutlined/> : i === 1 ? <ApartmentOutlined/> : <CompassOutlined/>}</span><span>{v}<small>{[8, 2, 1][i]} 个条目</small></span><ArrowRightOutlined/></button>)}</aside><section className="editor-canvas"><div className="canvas-header"><strong>{type} / {type === '配方' ? '精钢齿轮' : type === '结构' ? '废弃矿井' : '深层铜矿'}</strong><Tag color="green">校验通过</Tag></div>{type === '配方' ? <RecipeCanvas/> : <RuleCanvas type={type}/>}</section><aside className="editor-inspector"><div className="rail-label">检查栏</div><div className="inspect-ok"><CheckCircleFilled/> 当前内容可以应用</div><label>受影响模组</label><div className="inspect-tags"><Tag>Create</Tag><Tag>JEI</Tag></div><Divider/><label>最近修改</label><p className="db-muted">今天 10:24 · 你</p><Button block onClick={() => message.info('已撤销到上一版本')}>撤销上次修改</Button></aside></div></div>; }
function RecipeCanvas() { return <div className="recipe-canvas"><div className="recipe-slot"><span>铁锭</span><b>× 4</b></div><span className="recipe-plus">+</span><div className="recipe-slot"><span>安山合金</span><b>× 1</b></div><ArrowRightOutlined className="recipe-arrow"/><div className="recipe-slot output"><span>精钢齿轮</span><b>× 2</b></div><div className="canvas-foot">Create · shaped crafting · 3 × 3</div></div>; }
function RuleCanvas({type}: {type: string}) { return <div className="rule-canvas"><div className="rule-preview"><span className="preview-sky"/><span className="preview-ground"/><span className="preview-ore"/></div><div className="rule-fields"><label>{type === '结构' ? '生成频率' : '矿脉权重'}<InputNumber defaultValue={type === '结构' ? 18 : 42} min={0}/></label><label>最小高度<InputNumber defaultValue={-32}/></label><label>最大高度<InputNumber defaultValue={48}/></label></div></div>; }

const quests = [{name: '序章：抵达', count: 6, progress: 100}, {name: '第一章：点燃引擎', count: 8, progress: 62}, {name: '第二章：越过边界', count: 5, progress: 20}];
export function QuestEditorPage() { const [selected, setSelected] = useState('建立第一台机械'); const {message} = App.useApp(); return <div className="workspace-page editor-page"><PackContext active="任务书" action={<Space><Button icon={<CompassOutlined/>} onClick={() => message.info('预览模式已打开')}>预览任务书</Button><WorkbenchButton tone="primary" onClick={() => message.success('任务书已保存')}>保存</WorkbenchButton></Space>}/><div className="page-heading compact"><div><span className="eyebrow">QUEST BOOK</span><h1>任务书</h1><p>把整合包目标编排成一条可玩的路线，节点依赖会实时校验。</p></div></div><div className="quest-layout"><aside className="chapter-rail"><div className="rail-label">章节 <span>3</span></div>{quests.map((q, i) => <button key={q.name} className={i === 1 ? 'selected' : ''}><span className={`chapter-number chapter-${i}`}>{i + 1}</span><span><strong>{q.name}</strong><small>{q.count} 个任务 · {q.progress}% 完成</small></span><MoreOutlined/></button>)}<Button type="dashed" block icon={<PlusOutlined/>}>添加章节</Button></aside><section className="quest-canvas"><div className="canvas-header"><strong>第一章：点燃引擎</strong><span className="db-muted">8 个任务 · 2 条分支</span></div><div className="quest-map"><div className="quest-line line-a"/><div className="quest-line line-b"/><button className="quest-node done"><CheckCircleFilled/><span>收集铜矿</span><small>奖励已领取</small></button><button className={`quest-node selected ${selected === '建立第一台机械' ? 'is-selected' : ''}`} onClick={() => setSelected('建立第一台机械')}><ToolOutlined/><span>建立第一台机械</span><small>需要：Create</small></button><button className="quest-node" onClick={() => setSelected('自动化入门')}><CodeOutlined/><span>自动化入门</span><small>前置：建立第一台机械</small></button><button className="quest-node branch"><CompassOutlined/><span>去寻找遗迹</span><small>可选分支</small></button></div></section><aside className="quest-inspector"><div className="rail-label">节点属性</div><label>标题</label><Input value={selected} onChange={e => setSelected(e.target.value)} /><Input.TextArea defaultValue="让玩家完成第一台机械的组装，理解动力网络的基本关系。" rows={4} placeholder="任务描述"/><label>前置条件</label><Tag>收集铜矿</Tag><label>奖励</label><div className="reward-row"><span className="reward-icon">◆</span><span>安山合金 × 4</span><Button type="text">更换</Button></div><Button block icon={<PlusOutlined/>}>添加奖励</Button></aside></div></div>; }

export function PublishPage() { const {message} = App.useApp(); const [building, setBuilding] = useState(false); return <div className="workspace-page"><PackContext active="打包与发布" action={<WorkbenchButton tone="primary" loading={building} icon={<FileZipOutlined/>} onClick={() => {setBuilding(true); window.setTimeout(() => {setBuilding(false); message.success('整合包已打包完成');}, 900);}}>开始打包</WorkbenchButton>}/><div className="page-heading compact"><div><span className="eyebrow">DELIVERY / RELEASE</span><h1>打包与发布</h1><p>确认交付清单，再选择导出或发布目标。</p></div><Tag color="green">可打包</Tag></div><div className="release-layout"><main><WorkbenchCard className="release-check-card"><WorkbenchSectionHeader title="交付检查" action={<Button type="text" icon={<ReloadOutlined/>}>重新检查</Button>}/>{[['依赖锁定', '142 个模组的版本已锁定', true], ['冲突处理', '3 个冲突已全部解决', true], ['内容校验', '配方、结构、矿脉和任务书格式正确', true], ['版本号', 'v1.2.0 · NeoForge · MC 1.20.1', true], ['缺失文件', '没有发现缺失的必需文件', true]].map(([title, desc, ok]) => <div className="check-row" key={String(title)}><span className="check-icon">{ok ? <CheckCircleFilled/> : <WarningFilled/>}</span><div><strong>{title}</strong><span>{desc}</span></div><Tag color={ok ? 'green' : 'red'}>{ok ? '已通过' : '阻塞'}</Tag></div>)}</WorkbenchCard><WorkbenchCard className="artifact-card"><WorkbenchSectionHeader title="最近产物" action={<Button type="link" icon={<FolderOpenOutlined/>}>打开目录</Button>}/><div className="artifact-row"><FileZipOutlined/><div><strong>科技魔法-v1.2.0.zip</strong><span>1.8 GB · 今天 10:31</span></div><Tag color="green">已完成</Tag><Button type="text" icon={<ExportOutlined/>}>导出</Button></div></WorkbenchCard></main><aside className="target-rail"><h2>交付目标</h2><p>选择一个目标开始导出。发布前会再次执行完整校验。</p><TargetCard icon={<FileZipOutlined/>} title="本地导出" desc="生成可分享的 zip 文件" action="导出整包" onClick={() => message.success('正在生成本地导出')}/><TargetCard icon={<CloudDownloadOutlined/>} title="CurseForge" desc="发布到 CurseForge 项目" action="连接并发布" onClick={() => message.info('请先在设置中连接 CurseForge')}/><TargetCard icon={<CloudDownloadOutlined/>} title="Modrinth" desc="发布到 Modrinth 项目" action="连接并发布" onClick={() => message.info('请先在设置中连接 Modrinth')}/></aside></div><div className="release-steps"><Steps current={4} items={['检查', '版本', '说明', '平台', '打包'].map(title => ({title}))}/></div></div>; }
function TargetCard({icon, title, desc, action, onClick}: {icon: React.ReactNode; title: string; desc: string; action: string; onClick: () => void}) { return <div className="target-card"><span className="target-icon">{icon}</span><div><strong>{title}</strong><span>{desc}</span></div><Button type="link" onClick={onClick}>{action} <ArrowRightOutlined/></Button></div>; }

export function SettingsPage() { const {message} = App.useApp(); const [form] = Form.useForm(); return <div className="workspace-page settings-page"><div className="page-heading"><div><span className="eyebrow">WORKSPACE / PREFERENCES</span><h1>设置</h1><p>连接平台、管理存储，并定义新整合包的默认配置。</p></div><Button icon={<SettingOutlined/>}>恢复默认</Button></div><div className="settings-layout"><aside className="settings-rail"><button className="selected">平台连接</button><button>存储与缓存</button><button>默认包配置</button><button>界面</button></aside><main className="settings-main"><section className="settings-section"><WorkbenchSectionHeader title="平台连接"/><ProviderCard name="CurseForge" status="已连接" color="orange" onTest={() => message.success('CurseForge 连接正常')}/><ProviderCard name="Modrinth" status="已连接" color="blue" onTest={() => message.success('Modrinth 连接正常')}/></section><section className="settings-section"><WorkbenchSectionHeader title="存储与缓存" action={<Button type="link" icon={<DeleteOutlined/>}>清理缓存</Button>}/><div className="storage-line"><div><span>模组缓存</span><strong>1.2 GB / 10 GB</strong></div><Progress percent={12} showInfo={false}/><small>D:\\mPackStation\\cache · 剩余空间 86.4 GB</small></div></section><section className="settings-section"><WorkbenchSectionHeader title="默认包配置"/><Form form={form} layout="vertical" initialValues={{version: '1.20.1', loader: 'NeoForge', autoResolve: true}} onFinish={() => message.success('默认配置已保存')}><div className="form-grid"><Form.Item label="MC 版本" name="version"><Select options={['1.20.1', '1.21.1'].map(v => ({label: v, value: v}))}/></Form.Item><Form.Item label="加载器" name="loader"><Select options={['NeoForge', 'Forge', 'Fabric', 'Quilt'].map(v => ({label: v, value: v}))}/></Form.Item></div><Form.Item label="创建后自动处理" name="autoResolve" valuePropName="checked"><Switch checkedChildren="自动" unCheckedChildren="手动"/></Form.Item><Button type="primary" htmlType="submit" className="mc-btn-cta">保存默认配置</Button></Form></section></main></div></div>; }
function ProviderCard({name, status, color, onTest}: {name: string; status: string; color: string; onTest: () => void}) { return <div className="provider-card"><span className={`provider-mark provider-${color}`}><LinkOutlined/></span><div><strong>{name}</strong><span>API Key 已配置 · 上次检查 10 分钟前</span></div><Tag color="green">{status}</Tag><Button size="small" onClick={onTest}>测试连接</Button></div>; }
